FROM golang:1.14.6-alpine3.12

# Install git
RUN apk add --no-cache git

# Set the Current Working Directory inside the container
WORKDIR /bank-api

# Copy go mod and sum files 
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and the go.sum files are not changed 
RUN go mod download 

# Copy the source from the current directory to the working Directory inside the container 
COPY . .

# Run tests
CMD CGO_ENABLED=0 go test -v  ./...