version: '3'
services:
  app:
    container_name: app
    build: .
    ports: 
      - "127.0.0.1:8080:8080"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db-postgres
    networks:
      - app-db-network

  db-postgres:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - app-db-network

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  app-db-network:
    driver: bridge